@startuml


participant RemoveBookFromCatalogActivity
participant CatalogDao
participant CatalogItemVersion

RemoveBookFromCatalogActivity -> CatalogDao: getBookFromCatalog(bookId)
activate CatalogDao
CatalogDao -> CatalogItemVersion: getBook(bookId)
activate CatalogItemVersion
CatalogItemVersion --> CatalogDao: return catalogItem
deactivate CatalogItemVersion
CatalogDao -->RemoveBookFromCatalogActivity: return catalogItem
deactivate CatalogDao
RemoveBookFromCatalogActivity -> RemoveBookFromCatalogActivity: setInactive(catalogItem)
RemoveBookFromCatalogActivity ->CatalogDao: saveInactiveStatus(catalogItem)
activate CatalogDao
CatalogDao --> RemoveBookFromCatalogActivity: return response
deactivate CatalogDao

@enduml
```