@startuml
class GetBookActivity {
- recommendationServiceClient : RecommendationsServiceClient
- catalogDao : CatalogDao
+ execute(request : GetBookRequest) : GetBookResponse
}

class GetPublishingStatusActivity {
}

class RemoveBookFromCatalogActivity {
+ execute(request : RemoveBookFromCatalogRequest) : RemoveBookFromCatalogResponse
}

class SubmitBookForPublishingActivity {
- publishingStatusDao : PublishingStatusDao
+ execute(request : SubmitBookForPublishingRequest) : SubmitBookForPublishingResponse
}

class RecommendationsServiceClient {
}

class CatalogDao {
+ dynamoDBMapper : DynamoDBMapper
}

class PublishingStatusDao {
+ dynamoDBMapper : DynamoDBMapper
}

class PublishingStatusItem {
- @DynamoDBHashKey publishingRecordId : String
- @DynamoDBRangeKey status : PublishingRecordStatus
- statusMessage : String
- bookId : String

}

class CatalogItemVersion {
- @DynamoDBHashKey bookId : String
- @DynamoDBRangeKey version : int
- inactive : boolean
- title : String
- author : String
- text : String
- genre : BookGenre
}

enum BookGenre {
}

class BookNotFoundException {
}

class PublishingStatusNotFoundException {
}

GetBookActivity --> RecommendationsServiceClient
GetBookActivity --> CatalogDao
SubmitBookForPublishingActivity --> PublishingStatusDao
RemoveBookFromCatalogActivity --> CatalogDao
CatalogDao --> BookNotFoundException
CatalogItemVersion --> BookGenre
PublishingStatusItem --> PublishingRecordStatus
CatalogItemVersion --> CatalogDao
PublishingStatusItem --> PublishingStatusDao
@enduml

