@startuml
actor Client
participant RemoveBookFromCatalogActivity
participant CatalogDao
participant CatalogItemVersion


Client -> RemoveBookFromCatalogActivity: removeBookFromCatalog(bookId)
Client -> RemoveBookFromCatalogActivity: execute(bookId)
RemoveBookFromCatalogActivity -> CatalogDao: getBookFromCatalog(bookId)
CatalogDao -> CatalogItemVersion: getBook(bookId) : BookNotFoundException

CatalogItemVersion --> CatalogDao: return catalogItem
CatalogDao -->RemoveBookFromCatalogActivity: return catalogItem
RemoveBookFromCatalogActivity -> RemoveBookFromCatalogActivity: setInactive(catalogItem)
RemoveBookFromCatalogActivity ->CatalogDao: saveInactiveStatus(catalogItem)
CatalogDao --> RemoveBookFromCatalogActivity: return response
RemoveBookFromCatalogActivity -> Client: RemoveBookFromCatalogResponse

@enduml